### PR TITLE
Use custom config for CUSTOM track type; table definition and parser

### PR DESCRIPTION
**Pull request by helios**
The goal was to solve issue https://github.com/igvteam/igv-webapp/issues/171 avoiding as much as possible customization by users of the different component such as igv-widgets and data-modal. To make it possible a new CUSTOM type is present in  https://github.com/igvteam/igv-widgets/pull/51 and the system creates different buttons based on the number of datasources defined in `igvwebConfig.js`.
The user can define multiple "configurator" directly into `igvwebConfig.js`. In my case was generating statis tables formatted as CSV, so I decided to parse them using [Papaparser](https://www.papaparse.com/).
In order to avoid strong customization of the configurator and letting the user free do define some internal "parameters" I decided to use an inner dictionary in each track so that with one configurator multiple "buttons" can have independent origins even representing data with an equal structure.

`hg38_custom.json` file
```
{
    "label": "MAP-data",
    "type": "CUSTOM",
    "description": "<a href=hhttps://www.encodeproject.org/ target=_blank>Encylopedia of Genomic Elements</a>",
    "genomeID": "GRCh38",
   "configurator" : {
      "dataSetPath": "http://yourserver:8080/files/hg38/MAP/GRCh38.tracks-project_ext.txt",
      "suffix": ".tracks-project.txt",
      "dataSetPathPrefix": "https://yourserver/files/hg38/MAP/",
      "urlPrefix": "http://yourserver:8080/files/hg38/MAP/"                                                                                                                                                  }
}
```  

Some of the `keys` inside `configurator` are not used, are there because I was reusing the "enconde" example; but looking into `igvwegConfig.js` is possible to see how to reuse `dataSetPathPrefix` similarly as done with the Encode datasource.

### CODE REVIEW

**Comment by jrobinso** [comment]
OK thanks, we'll look at this next week.

**Comment by turner** [comment]
helios, I am reviewing your PR branch issue_171_revised and do not see hg38_custom.json?

**Comment by turner** [comment]
Can you clarify where you define the dataSource configurator? In the above you have it defined in the button specific json. In the webapp code it is defined as a part of the app configuration - igvwebConfig.js.

Also, can you please indicate which branchs from igv-widgets and igv-webapp are intended to work together. I do not see the code in the branchs that corresponds to what you say in the PRs

**Comment by helios** [comment]
Thanks for reviewing the PR, I'll try explaing it better clarifying as much as I can. I realized that I perhaps used the term `configurator` multiple times in a confusing manner.

### About `hg38_custom.json`
I did not include the file in the repository because it was just an example for a temptative `.json` file that can be referenced by a custom `trackRegistry.json`. Follows a partial `trackRegistry.json` that includes the referenence to a `hg38_custom.json` file which is indeed the above
```
"hg38": [
    "resources/tracks/hg38_annotations.json",
    "resources/tracks/hg38_encode.json",
    "resources/tracks/hg38_1KG_lowCoverageCrams.json",
     "resources/tracks/hg38_custom.json"
  ],
```

in order to avoid multiple definitions of a very similar functions  such as `encodeTrackDatasourceSignalConfigurator(genomeID)` and `encodeTrackDatasourceOtherConfigurator(genomeID)` where what actually change are for example the inner values associated with the keys:
```
  suffix: '.other.txt',
  dataSetPathPrefix: 'https://www.encodeproject.org',
  urlPrefix: 'https://s3.amazonaws.com/igv.org.app/encode/',
  dataSetPath: undefined,
...
``` 
_BTW, I totally agree with the choice of having those functions defined for a very stable and important datasource._

I decided to experiment the possibility of having a [user defined dataSource configurator `customTrackDatasourceConfigurator `](https://github.com/helios/igv-webapp/blob/issue_171_revised/igvwebConfig.js#L2) that creates a basic configuration objects at [runtime](https://github.com/helios/igv-widgets/blob/issue_171_revised/src/trackWidgets.js#L253) without the need to modify the original `data-modal`. Then,  using the `configurator` key available in the button `hg38_custom.json` the default values returned by `customTrackDatasourceConfigurator ` are [override at runtime](https://github.com/helios/igv-widgets/blob/issue_171_revised/src/trackWidgets.js#L254). Following this approach, I can define multiple datasources only adding more button specific `.json` with few more parameters. This means, I can provide to my colleagues only access to the "tracks" path so they can add their own datasources.

This works with homogeneous datasources (columns). In case of multiple datasources with a different structures the IGV maintainer can create multiple dataSourceConfigurators still in the main `igvwebConfig.js file. I picked up the `igvwebConfig.js` because was easier for me testing the code there.

### How user defined dataSource is/are consumed?

[multiple ids with their dataSouceConfigurator](https://github.com/helios/igv-webapp/blob/issue_171_revised/igvwebConfig.js#L74) are passed to the [`createTrackWidgetsWithTrackRegistry`](https://github.com/helios/igv-webapp/blob/issue_171_revised/js/app.js#L111). I did a mistake reporting only a single `hg38_custom.json` in the PR message, following the [current example](https://github.com/helios/igv-webapp/blob/issue_171_revised/igvwebConfig.js#L74) another `hg38_custom_second.json` file should be present/references in the tracks.

### Branches intended to work together

* [igv-widgets 70b34e6a](https://github.com/igvteam/igv-widgets/commit/70b34e6a8312ae3fea261d53e9412b8e6362d435)
* [igv-webapp 1e1338b1](https://github.com/igvteam/igv-webapp/commit/1e1338b111b0bbf61d9f1f956f5397f4f79d1f46) this includes the latest igv-utils which I was using locally. I did not change the igv-utils version in my fork because i was not confident in changing the version in your `package.json` in the main `igv-webapp`.

I hope I was able to explain myself better than I did the first time.

**Comment by tweep** [comment]
Hey @helios ,
I just stumbled across your PR - I've been thinking / working on a separate feature based on JSON input similar to aidenlab's hicfiles.json format , however i am a bit stuck now as i noticed i have to also push some changes to the igv-widgets. let's see how this goes. Ideally, there would be an easy-to-configure, JSON based data structure which we could 'inject' ...

**Comment by jrobinso** [comment]
@tweep I'm also the author of the json labs widget and "juicebox".  We've been covered up with other things and haven't been able to get to this PR yet.   If you're referring to the json to load contact maps via the table based loader then yes that is the direction we will go.   When I find time to study this PR and compare to that I'll update this conversation.   Probably not before next week.   But in the end I expect something close to the hic project approach,  well really its the same project as this one we will definitely have a shared solution.

**Comment by tweep** [comment]
Thanks for the quick response, @jrobinso  
and Yes - i was referring to your `js/aidenLabContactMapDatasourceConfig.js` in igv's `data-modal `. I really liked your approach of using JSON and tried to extend it, however I only realized today that I've got to modify the widgets too. 

An ideal solution for me would be similar to @helios approach to have this configurable in a separate dict somewhere upstream, ie. in the trackRegistry.json so can be re-used easily by other teams without modifying the widgets or creating new configurators for every track.  I was also thinking to add hiding/un-hiding columns (via json config, not via UI). How did you integrate your ContactMapDataSource without modifying the widgets ?

**Comment by jrobinso** [comment]
@tweep  Give us a week or two and we should have something to propose.   Definitely it will be through configuration and not modification of igv-widgets.   The purpose of that project is to share code between igv-webapp and juicebox-web.

**Comment by tweep** [comment]
Hey there ! Any updates ? can we help ?

**Comment by helios** [comment]
@tweep There is a small update that I was to share with you.
We had some trouble using the `igv.js` referenced in the `index.html` because it points to the on-line version, the most up to date. I notice that with my "code" after a while the code started to brokeup; I guess it diverged a lot form my "old-stable" version compared to the upstream/master.
My solution was to going back in time and search for a version of `igv.js` that worked with my inital tests. So I found that commit id: f98e31c7ca works.  With the following installation importing session does not work properly, but the remaining functionalities are OK. A work around: you can retrieve the URL link from ‘Shared’, save it in your notes and use it at a later time or share it with others.

To be honest I do not remember if I shared here the full installation guide. I am using Docker containers so this is my current/live `Dockerfile`

```
FROM openresty/openresty:1.17.8.1-centos
RUN yum install -y curl &&\
curl -sL https://rpm.nodesource.com/setup_14.x | bash - &&\
    yum install -y nodejs
RUN yum install -y git
WORKDIR /opt/
RUN git clone https://github.com/helios/igv-widgets.git 
WORKDIR /opt/igv-widgets
RUN git fetch --all &&\
    rm -rf node_modules &&\
    git checkout issue_171_revised &&\
    npm install &&\
    npm install &&\
    npm run build

WORKDIR /opt/
RUN git clone https://github.com/helios/igv-webapp.git
WORKDIR /opt/igv-webapp
RUN git fetch --all &&\
   rm -rf node_modules &&\
   git checkout 47f4a41 &&\
   sed -i 's#"igv-widgets":.*$#"igv-widgets": "file:../igv-widgets",#g;s#8ee6a6e8#2c9085f#g' package.json &&\
    npm install &&\
    npm run build

ADD igvwebConfig.js ./
RUN mv dist/* /usr/local/openresty/nginx/html
RUN mv node_modules /usr/local/openresty/nginx
WORKDIR /opt/
RUN git clone https://github.com/igvteam/igv.js.git
WORKDIR /opt/igv.js
RUN git fetch --all &&\
    git checkout f98e31c7ca &&\
    npm install &&\
    npm run build &&\
    mv dist/igv.js /usr/local/openresty/nginx/html/
WORKDIR /usr/local/openresty/nginx/html
RUN sed -i 's#https://igv.org/web/snapshot/dist/igv.js#igv.js#g' index.html
WORKDIR /opt/
RUN rm -rf /opt/igv.js
RUN yum remove -y diffutils patch git nodejs
RUN yum clean all
```

I am really happy to discuss with whom interested or help even on the main libraries. I can understand that with a so frequent development cicles including new features can raise stability issues.

**Comment by jrobinso** [comment]
> Hey there ! Any updates ? can we help ?

@tweep Thanks for the offer but what's required unfortunately is some of my time to review and get my head around the options.   We've been covered up trying to get major release done that has taken way more time than expected.   This is a priority for me and we'll get to it as soon as we get this out, which should be within a few days.   @turner @helgathorv

**Comment by jrobinso** [comment]
Hi @helios, @tweep , and anyone else following this.  Sorry for the delay.  In reviewing this (not the PR only, but the whole system),  it quickly became clear that our data-modal project needed a revamp for re-usability and to create a long term sustainable (and explainable) option for accomplishing this.   Part of that is complete, the data-modal revamp,  we now need to implement an easy means to specify these modal from igv-webapp (most of the work is in igv-widgets).    Unfortunately we are shutting down for a week, so it will be early December before we pick this up again, but should wrap it up shortly after that.   We can then revist this PR to see if there is anything not addressed.    Thanks for your patience.

In the meantime check out the revised [data-modal](https://github.com/igvteam/igv) project, particularly the examples, to see the types of options envisioned.

**Comment by helios** [comment]
@jrobinso ultra busy and yet time to read all the changes, but still very interested on this.

**Pull request closed without merging**
